#Question 1
Write a function called proportion_of_education which returns the proportion of children in the dataset who had a mother with the education levels equal to less than high school (<12), high school (12), more than high school but not a college graduate (>12) and college degree.

This function should return a dictionary in the form of (use the correct numbers, do not round numbers):

    {"less than high school":0.2,
    "high school":0.4,
    "more than high school but not college":0.2,
    "college":0.2}

In [ ]:
# lets load our dataset
import pandas as pd 
df = pd.read_csv("/content/NISPUF17.csv", index_col=0)
df.head()

SEQNUMC  SEQNUMHH  PDAT    PROVWT_D     RDDWT_D  STRATUM  YEAR  AGECPOXR  \
1   128521     12852     2         NaN  235.916956     1031  2017       NaN   
2    10741      1074     2         NaN  957.353840     1068  2017       NaN   
3   220011     22001     2         NaN  189.611299     1050  2017       NaN   
4    86131      8613     1  675.430817  333.447418     1040  2017       NaN   
5   227141     22714     1  482.617748  278.768063     1008  2017       NaN   

   HAD_CPOX  AGEGRP  ...  XVRCTY2  XVRCTY3  XVRCTY4  XVRCTY5  XVRCTY6  \
1         2       1  ...                        NaN      NaN      NaN   
2         2       1  ...                        NaN      NaN      NaN   
3         2       3  ...                        NaN      NaN      NaN   
4         2       1  ...                        NaN      NaN      NaN   
5         2       1  ...                        NaN      NaN      NaN   

   XVRCTY7  XVRCTY8  XVRCTY9  INS_STAT2_I  INS_BREAK_I  
1      NaN      NaN      NaN          NaN          NaN  
2      NaN      NaN      NaN          NaN          NaN  
3      NaN      NaN      NaN          NaN          NaN  
4      NaN      NaN      NaN          1.0          2.0  
5      NaN      NaN      NaN          2.0          1.0  

[5 rows x 453 columns]

In [ ]:
df.columns

Index(['SEQNUMC', 'SEQNUMHH', 'PDAT', 'PROVWT_D', 'RDDWT_D', 'STRATUM', 'YEAR',
       'AGECPOXR', 'HAD_CPOX', 'AGEGRP',
       ...
       'XVRCTY2', 'XVRCTY3', 'XVRCTY4', 'XVRCTY5', 'XVRCTY6', 'XVRCTY7',
       'XVRCTY8', 'XVRCTY9', 'INS_STAT2_I', 'INS_BREAK_I'],
      dtype='object', length=453)

In [ ]:
# EDUC1 is column for education of mother
df['EDUC1'].head()

1    4
2    3
3    3
4    4
5    1
Name: EDUC1, dtype: int64

In [ ]:
# lets get the values of EDUC1 column
edu_values = df['EDUC1'].unique()
edu_values

array([4, 3, 1, 2])

In [ ]:
# 1 for <12 years
# 2 for 12 years
# 3 for >12 years, not a college graduate
# 4 for College graduate

In [ ]:
def proportion_of_education():
  mother_dict = {}
  edu_values = df['EDUC1'].unique()
  for x in edu_values:
    #mother_dict[x] = len(row[row['EDUC1'] == x]) / len(row.index)
    mother_dict[x] = len(df[df['EDUC1'] == x]) / len(df.index)
  return mother_dict

In [ ]:
proportion_of_education()

{1: 0.10202002459160373,
 2: 0.172352011241876,
 3: 0.24588090637625154,
 4: 0.47974705779026877}

#Question 2
Let's explore the relationship between being fed breastmilk as a child and getting a seasonal influenza vaccine from a healthcare provider. Return a tuple of the average number of influenza vaccines for those children we know received breastmilk as a child and those who know did not.

This function should return a tuple in the form (use the correct numbers:

(2.5, 0.1)

In [ ]:
'CBF_01' in df.columns

True

In [ ]:
# 'CBF_01' column for child ever fed breast milk

# lets see few first data of this column
df['CBF_01'].head()

1    1
2    2
3    2
4    2
5    1
Name: CBF_01, dtype: int64

In [ ]:
# lets see the possible values of this column
cbf_values = df['CBF_01'].unique()
cbf_values.sort()
cbf_values

array([ 1,  2, 77, 99])

In [ ]:
# the CBF_01 column have 4 possible value
# 1 for Yes
# 2 for No
# 77 for Don't Know
# 99 for Missing

In [ ]:
# P_NUMFLU – total number of seasonal influenza doses
df['P_NUMFLU'].head(20)

1     NaN
2     NaN
3     NaN
4     3.0
5     0.0
6     NaN
7     0.0
8     0.0
9     0.0
10    NaN
11    3.0
12    NaN
13    3.0
14    NaN
15    NaN
16    NaN
17    3.0
18    NaN
19    NaN
20    2.0
Name: P_NUMFLU, dtype: float64

In [ ]:
def avg_cbf_numflu():
  # filter dataset, only contain columns of interest
  cbf_flu = df[['CBF_01', 'P_NUMFLU']]
  cbf_flu = cbf_flu.dropna()

  # lets get the total number of children who has received breast feed and not
  n_yes = len(cbf_flu[cbf_flu['CBF_01'] == 1])
  n_no = len(cbf_flu[cbf_flu['CBF_01'] == 2])

  avg_yes = cbf_flu[cbf_flu['CBF_01'] == 1]['P_NUMFLU'].sum() / n_yes
  # alternative
  # cbf_flu[cbf_flu['CBF_01'] == 1].loc[:,'P_NUMFLU'].sum()
  avg_no = cbf_flu[cbf_flu['CBF_01'] == 2]['P_NUMFLU'].sum() / n_no

  return (avg_yes, avg_no)





In [ ]:
avg_cbf_numflu()

(1.8799187420058687, 1.5963945918878317)

# Question 3
It would be interesting to see if there is any evidence of a link between vaccine effectiveness and sex of the child. Calculate the ratio of the number of children who contracted chickenpox but were vaccinated against it (at least one varicella dose) versus those who were vaccinated but did not contract chicken pox. Return results by sex.

This function should return a dictionary in the form of (use the correct numbers):

    {"male":0.2,
    "female":0.4}

In [ ]:
import pandas as pd
df = pd.read_csv('/content/NISPUF17.csv', index_col=0)
df.head()

SEQNUMC  SEQNUMHH  PDAT    PROVWT_D     RDDWT_D  STRATUM  YEAR  AGECPOXR  \
1   128521     12852     2         NaN  235.916956     1031  2017       NaN   
2    10741      1074     2         NaN  957.353840     1068  2017       NaN   
3   220011     22001     2         NaN  189.611299     1050  2017       NaN   
4    86131      8613     1  675.430817  333.447418     1040  2017       NaN   
5   227141     22714     1  482.617748  278.768063     1008  2017       NaN   

   HAD_CPOX  AGEGRP  ...  XVRCTY2  XVRCTY3  XVRCTY4  XVRCTY5  XVRCTY6  \
1         2       1  ...                        NaN      NaN      NaN   
2         2       1  ...                        NaN      NaN      NaN   
3         2       3  ...                        NaN      NaN      NaN   
4         2       1  ...                        NaN      NaN      NaN   
5         2       1  ...                        NaN      NaN      NaN   

   XVRCTY7  XVRCTY8  XVRCTY9  INS_STAT2_I  INS_BREAK_I  
1      NaN      NaN      NaN          NaN          NaN  
2      NaN      NaN      NaN          NaN          NaN  
3      NaN      NaN      NaN          NaN          NaN  
4      NaN      NaN      NaN          1.0          2.0  
5      NaN      NaN      NaN          2.0          1.0  

[5 rows x 453 columns]

In [ ]:
# P_NUMVRC – total number of varicella doses
df['P_NUMVRC'].head()

1    NaN
2    NaN
3    NaN
4    1.0
5    0.0
Name: P_NUMVRC, dtype: float64

In [ ]:
# HAD_CPOX – did child ever have chicken pox
print(df['HAD_CPOX'].head())
print(df['HAD_CPOX'].unique())

1    2
2    2
3    2
4    2
5    2
Name: HAD_CPOX, dtype: int64
[ 2  1 77 99]


In [ ]:
# HAD_CPOX value
# 1 for yes
# 2 for no

In [ ]:
# SEX – sex of child
df['SEX'].head()

1    1
2    1
3    2
4    2
5    2
Name: SEX, dtype: int64

In [ ]:
# SEX value
# 1 for Male
# 2 for Female

In [ ]:
# filter columns that only show columns that we are interested in
df1 = df[['SEX', 'P_NUMVRC', 'HAD_CPOX']]
df1 = df1.dropna()
df1.head()

SEX  P_NUMVRC  HAD_CPOX
4    2       1.0         2
5    2       0.0         2
7    2       1.0         2
8    2       0.0         2
9    1       0.0         1

In [ ]:
# number of children wo received vaccine (at least 1 dose) but had_cpox
# male children
df_male = df1[df1['SEX'] == 1]
df_male.head()

SEX  P_NUMVRC  HAD_CPOX
9     1       0.0         1
11    1       1.0         2
13    1       1.0         2
17    1       2.0         2
20    1       1.0         2

In [ ]:
df_male['P_NUMVRC'].unique()

array([0., 1., 2., 3.])

In [ ]:
# filter male children who had at least 1 dose
df_male = df_male[df_male['P_NUMVRC'] != 0.0]
df_male.head()

SEX  P_NUMVRC  HAD_CPOX
11    1       1.0         2
13    1       1.0         2
17    1       2.0         2
20    1       1.0         2
22    1       1.0         2

In [ ]:
# total number of male child who were vaccinated but did not contract chicken pox
male_no = len(df_male[df_male['HAD_CPOX'] == 2].index)
male_no

7028

In [ ]:
# total number of male child who were vaccinated but had contract with chicken pox
male_yes = len(df_male[df_male['HAD_CPOX'] == 1].index)
male_yes

68

In [ ]:
ratio_male = male_yes / male_no
ratio_male

0.009675583380762664

In [ ]:
# number of children wo received vaccine (at least 1 dose) but had_cpox
# female children
df_female = df1[df1['SEX'] == 2]
df_female.head()

SEX  P_NUMVRC  HAD_CPOX
4     2       1.0         2
5     2       0.0         2
7     2       1.0         2
8     2       0.0         2
21    2       1.0         2

In [ ]:
# filter male children who had at least 1 dose
df_female = df_female[df_female['P_NUMVRC'] != 0.0]
df_female.head()

SEX  P_NUMVRC  HAD_CPOX
4     2       1.0         2
7     2       1.0         2
21    2       1.0         2
23    2       1.0         2
25    2       1.0         2

In [ ]:
# total number of female child who were vaccinated but did not contract chicken pox
female_no = len(df_female[df_female['HAD_CPOX'] == 2].index)
female_no

6802

In [ ]:
# total number of female child who were vaccinated but had contract chicken pox
female_yes = len(df_female[df_female['HAD_CPOX'] == 1].index)
female_yes

53

In [ ]:
ratio_female = female_yes / female_no
ratio_female

0.0077918259335489565

In [ ]:
ratio_child = {'male': ratio_male, 'female': ratio_female}
ratio_child

{'female': 0.0077918259335489565, 'male': 0.009675583380762664}

In [ ]:
def chickenpox_by_sex():
  import pandas as pd 
  df = pd.read_csv('/content/NISPUF17.csv', index_col=0)
  df = df[['SEX', 'P_NUMVRC', 'HAD_CPOX']]
  df = df.dropna() 
  df_male = df[df['SEX'] == 1]
  df_female = df[df['SEX'] == 2]

  # male vacine had cpox
  male_cpox = len(df_male[(df_male['P_NUMVRC'] != 0.0) & (df_male['HAD_CPOX'] == 1)])
  male_no_cpox = len(df_male[(df_male['P_NUMVRC'] != 0.0) & (df_male['HAD_CPOX'] == 2)])
  
  ratio_males = male_cpox / male_no_cpox
  # male vacine had cpox
  female_cpox = len(df_female[(df_female['P_NUMVRC'] != 0.0) & (df_female['HAD_CPOX'] == 1)])
  female_no_cpox = len(df_female[(df_female['P_NUMVRC'] != 0.0) & (df_female['HAD_CPOX'] == 2)])
  ratio_females = female_cpox / female_no_cpox
  return {'male': ratio_males, 'female': ratio_females}

In [ ]:
chickenpox_by_sex()

{'female': 0.0077918259335489565, 'male': 0.009675583380762664}

# Question 4
A correlation is a statistical relationship between two variables. If we wanted to know if vaccines work, we might look at the correlation between the use of the vaccine and whether it results in prevention of the infection or disease [1]. In this question, you are to see if there is a correlation between having had the chicken pox and the number of chickenpox vaccine doses given (varicella).

Some notes on interpreting the answer. The had_chickenpox_column is either 1 (for yes) or 2 (for no), and the num_chickenpox_vaccine_column is the number of doses a child has been given of the varicella vaccine. A positive correlation (e.g., corr > 0) means that an increase in had_chickenpox_column (which means more no’s) would also increase the values of num_chickenpox_vaccine_column (which means more doses of vaccine). If there is a negative correlation (e.g., corr < 0), it indicates that having had chickenpox is related to an increase in the number of vaccine doses.

Also, pval is the probability that we observe a correlation between had_chickenpox_column and num_chickenpox_vaccine_column which is greater than or equal to a particular value occurred by chance. A small pval means that the observed correlation is highly unlikely to occur by chance. In this case, pval should be very small (will end in e-18 indicating a very small number).

[1] This isn’t really the full picture, since we are not looking at when the dose was given. It’s possible that children had chickenpox and then their parents went to get them the vaccine. Does this dataset have the data we would need to investigate the timing of the dose?

In [3]:
import pandas as pd
import scipy.stats as stats
import numpy as np
base_url = "https://drive.google.com/file/d/1A7To9Jq1oBoi9cx6Bo_TDV8pKL7sscAf/view?usp=sharing"
url = "https://drive.google.com/uc?id=" + base_url.split('/')[-2]
df = pd.read_csv(url, index_col=0)
df.head()

SEQNUMC  SEQNUMHH  PDAT    PROVWT_D     RDDWT_D  STRATUM  YEAR  AGECPOXR  \
1   128521     12852     2         NaN  235.916956     1031  2017       NaN   
2    10741      1074     2         NaN  957.353840     1068  2017       NaN   
3   220011     22001     2         NaN  189.611299     1050  2017       NaN   
4    86131      8613     1  675.430817  333.447418     1040  2017       NaN   
5   227141     22714     1  482.617748  278.768063     1008  2017       NaN   

   HAD_CPOX  AGEGRP  ...  XVRCTY2  XVRCTY3  XVRCTY4  XVRCTY5  XVRCTY6  \
1         2       1  ...                        NaN      NaN      NaN   
2         2       1  ...                        NaN      NaN      NaN   
3         2       3  ...                        NaN      NaN      NaN   
4         2       1  ...                        NaN      NaN      NaN   
5         2       1  ...                        NaN      NaN      NaN   

   XVRCTY7  XVRCTY8  XVRCTY9  INS_STAT2_I  INS_BREAK_I  
1      NaN      NaN      NaN          NaN          NaN  
2      NaN      NaN      NaN          NaN          NaN  
3      NaN      NaN      NaN          NaN          NaN  
4      NaN      NaN      NaN          1.0          2.0  
5      NaN      NaN      NaN          2.0          1.0  

[5 rows x 453 columns]

In [4]:
df = df[['HAD_CPOX', 'P_NUMVRC']].dropna()
df.head()

HAD_CPOX  P_NUMVRC
4         2       1.0
5         2       0.0
7         2       1.0
8         2       0.0
9         1       0.0

In [6]:
corr, p_value = stats.pearsonr(df['HAD_CPOX'], df['P_NUMVRC'])

In [7]:
corr

0.003475317151529345

In [8]:
p_value

0.6669755758983259